services:
 web:
   image: vote-apache-picot
   ports:
     - "68:80"
   depends_on:
     - db

 db:
   image: vote-mysql-picot
   environment:
     MYSQL_ROOT_PASSWORD: P@ssw0rdEN24

 phpmyadmin:
  image: phpmyadmin
  restart: always
  ports:
    - 8068:80
  environment:
    - PMA_ARBITRARY=1
