services:
 web:
   image: vote-apache
   ports:
     - "80:80"

 db:
   image: vote-mysql
   environment:
     MYSQL_ROOT_PASSWORD: P@ssw0rdEN24

 phpmyadmin:
  image: phpmyadmin
  restart: always
  ports:
    - 8080:80
  environment:
    - PMA_ARBITRARY=1
